<a href="https://colab.research.google.com/github/chetools/CHE4061_Spring2026/blob/main/dynamic_distillation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -N -q https://raw.githubusercontent.com/chetools/chetools/main/tools/che5.ipynb -O che5.ipynb
%run che5.ipynb

In [ ]:
#y = alpha*x/(1-x+alpha*x)

In [24]:
alpha = 2.
F = 1.
zF = 0.45
q=1.  #all liquid feed
Dsp = 0.55*F

N= 7
NFeed = 4
M0stage = 10.
M0cond = 50.
M0boil = 100.
c = 4.  #weir constant

In [4]:
M0 = np.r_[M0cond, N*[M0stage], M0boil]

In [5]:
M0

array([ 50.,  10.,  10.,  10.,  10.,  10.,  10.,  10., 100.])

In [22]:
M = np.r_[1.2*M0cond, N*[15], 1.1*M0boil]
L = c*np.where(M<M0, 0, (M-M0))**1.5
dM = np.zeros_like(M)
dM -= L
dM[1:]+=L[:-1]
dM[:NFeed]+=Vrec


R = 2
Vrec = (R+1)*Dsp
Vstrip = Vrec - (1-q)*F



In [23]:
dM

array([-126.49110641,   81.76974686,    0.        ,    0.        ,
          0.        ,    0.        ,    0.        ,    0.        ,
        -81.76974686])

In [6]:
# 0    1     2    3       F
# 50.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10., 100.

In [ ]:
def rhs(t, vec):
    R = 2.
    M = vec
    L = c*np.where(M<M0, 0, (M-M0))**1.5

    D = L[0]/(R+1)

    dM = np.zeros_like(M)
    dm




array([ 50.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10., 100.])