<a href="https://colab.research.google.com/github/chetools/CHE4061_Spring2026/blob/main/LLE_GibbsEnergyMinimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget -N -q https://raw.githubusercontent.com/chetools/chetools/main/tools/che5.ipynb -O che5.ipynb
%run che5.ipynb

In [ ]:
import scipy as sp

In [ ]:
p=Props(["Isopropanol","Water","Toluene"])

In [ ]:
F = np.array([9,0.5,0.5])
T=300.

In [ ]:
k0 = np.array([0.5, 0.01, 0.99])

In [ ]:
def G(k):
    L1 = k*F
    L2 = F-L1
    x1 = L1/jnp.sum(L1)
    x2 = L2/jnp.sum(L2)
    gamma1 = p.NRTL_gamma(x1, T)
    gamma2 = p.NRTL_gamma(x2, T)
    return jnp.sum(L1*jnp.log(gamma1*x1) + L2*jnp.log(gamma2*x2))


In [ ]:
jac = jax.jacobian(G)

In [ ]:
res = sp.optimize.minimize(G, k0,bounds=[(0,1)]*3, method='SLSQP', jac=jac, tol=1e-12)

In [ ]:
ksol = res.x

In [ ]:
L1 = ksol*F
L2 = F - L1
L1, L2

(array([3.54561042, 0.19697839, 0.19697832]),
 array([5.45438958, 0.30302161, 0.30302168]))

In [ ]:
L1/np.sum(L1)

array([0.9       , 0.05000001, 0.04999999])

In [ ]:
L2/np.sum(L2)

array([0.9       , 0.04999999, 0.05000001])

In [ ]:
#(array([1.72390912, 0.06896073, 4.49850777]),
# array([2.76090883e-01, 3.43103927e+00, 1.49222744e-03]))